SHELL = /bin/sh

OUTPUT := $(PWD)
TMP_IDX :=../index.html

RUN_JAVA: 
	echo $(PWD)
	/usr/bin/java -cp ../target/database-diagrams-1.0-SNAPSHOT.jar com.github.krismorte.databasediagrams.Main $(OUTPUT) $(TMP_IDX)