FROM openjdk:8-jdk-alpine3.9
MAINTAINER krisnamourt_ti@hotmail.com

ENV CRN='0 7 * * *'
ENV OUTPUT=/www
ENV LOGFILE=/var/log/script.log
ENV TMP_IDX=index.html

RUN mkdir src
RUN mkdir -p /run/nginx
COPY src/ src/
COPY dbconf/ dbconf/
COPY pom.xml .
COPY index.html .

RUN apk update && apk add --no-cache graphviz && apk add ttf-opensans && apk add maven && apk add nginx
RUN mvn package && wget github.com/schemaspy/schemaspy/releases/download/v6.0.0/schemaspy-6.0.0.jar -O schemaspy.jar

ENTRYPOINT [ "mvn","exec:java"]
