version: '3'
services:
  mysql:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
    volumes:
      - "$PWD/dbconf/mysql:/docker-entrypoint-initdb.d"
  mysql2:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
  pgsql:
    image: postgres:15.6
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=secret"
    volumes:
      - "$PWD/dbconf/pgsql:/docker-entrypoint-initdb.d"
  database-diagrams:
    build: .
    ports:
      - "80:80"
    volumes:
      - "$PWD/dbconf:/dbconf"
    depends_on:
      - mysql
      - mysql2
      - pgsql
